travis:
  secure:
    BINSTAR_TOKEN: UelD9P76u590DKQgyD4AidnogMxEfN1H0HHFALb71bsx/ZgGP0R3nsEYSUOt7cuV6WxdX1zL4wxWbwuL8iwDdagABkGa+w6rVUFtIDJ4bwJXf1ILAFTDW0W4vSJLg49r+3hpSWB77YnJAfDxRUTjmUzyjCDANv/WGBGSab61nlker1E0HdO7hEjwDrP3cXCiO75K1Fs8CkICaQfp4EAWjvJ0a1LZoyhRgx+g0dj92609t9jKuEIxQXtC8n1djMednJizRwLD1099hjv4O/GkPLCON+QAhUGfk4zCb6mV8WKbay59Fzu9C0dgkzyFr7YpUkW6n1uhT5crd6OgTrKiSdX+bjQqvnBMe+AvnTn8lhUmPJCyqzG3BqolPVvG/LgkEmI34yafBrBPnK505pMFCCtFyTFM1o8fIUMYj5xtbaJpHaMdnfgToVK73rYlnd1rNX9fqW+KWla223xtlOgktHv6TgHLA5Ff+G0dn+oVoOnpULlVocOkQquM+5hwDnfDHTkiStAISiwIi/O9XIswtA8dpud+vGcaKQ9Jjr4JtxKkOKn0Ra37lSgodZx5w4FMYFftgyEqvYKXAkAVGLdyCpvHCGVdi+400mzg52p+NAnSu7LtnxDd6mzLhxRPPGKvmXo8o+XOBWror5vwDH1IZXol+W8JtDGGcCREnki2/Nc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
